#!/bin/bash
# Copyright (c) 2011 Martin Ueding <dev@martin-ueding.de>

# This assumes that you are in the head of a git repository. If not, the script
# will just fail at some point when trying to check out the branch.

set -e
set -u

logfile=$(date +%s)_$(uuidgen).log

exec > $logfile 2>&1

git checkout master
make
